### PR TITLE
#20 respect pit_end_time in case of dmarkers

### PR DESCRIPTION
**Pull request by Barala**
This is to fix issue: https://github.com/madisoft/s3-pit-restore/issues/20

### CODE REVIEW

**Comment by angeloc** [comment]
@Barala : Thanks for your PR!

Only a nitpick, could you add a test case for this case?

Thanks!

**Comment by angeloc** [comment]
> ----------------------------------------------------------------------
> Ran 2 tests in 154.128s
> 
> OK

Good job! Wonderful!

> BTW why below cases are not supported? any particular reason?
>     * Restore within s3 bucket 
>     * Restore across s3 buckets

Lack of time, you can contribute of course!

**Comment by Barala** [comment]
@angeloc Ok, I'll open PR for those too. Thanks!!

**Comment by angeloc** [comment]
> @angeloc Ok, I'll open PR for those too. Thanks!!

Please take a look at other PRs, one of em is about adding another bucket as destination (https://github.com/madisoft/s3-pit-restore/pull/11), PR was opened but never updated after I asked for some fixings.
It would be awesom if you can resurrect that and doing it the right way (testing also).

**Pull request merged**
